services:
  - type: web
    name: hospital-appointment-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://d2024vanshikaahuja_db_user:Vanshika@cluster0.jdbxboe.mongodb.net/hospital_appointment?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://hospital-appointment.vercel.app
  - type: web
    name: hospital-appointment-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://hospital-appointment-backend-t3jg.onrender.com
