services:
  - type: web
    name: hospital-appointment-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install --production
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: hospital-appointment-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://hospital-appointment.vercel.app

databases:
  - name: hospital-appointment-db
    plan: free
    databaseName: hospital_appointment
